### PR TITLE
Translation - Vetores do stringr: frutas, palavras, frases #89

### LINKED ISSUE #89: Translate dataset stringr::fruit - used in the regexps chapter from R4DS

### LINKED ISSUE #90: Translate dataset stringr::words - used in the regexps chapter from R4DS

### LINKED ISSUE #91: Translate dataset stringr::sentences - used in the regexps chapter from R4DS

### PR DESCRIPTION
**Pull request by beatrizmilz**

### CODE REVIEW

**Comment by beatrizmilz** [comment]
@rivaquiroga Hi! Can you review this PR?

**Comment by rivaquiroga** [comment]
Sure! I'll work on this tomorrow morning

**Comment by beatrizmilz** [comment]
> Sure! I'll work on this tomorrow morning

Thank you so much!

**Comment by rivaquiroga** [comment]
Done!

**Comment by beatrizmilz** [comment]
> Done!

Thank you so much Riva!

**Pull request merged**
